-- Truncate all application tables except User
-- Disable FKs
SET session_replication_role = replica;

-- Truncate tables (reverse dependency order) and restart identities
TRUNCATE TABLE "ActivityLog" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Attendance" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Grade" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Enrollment" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Scholarship" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "FamilyInfo" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Guardian" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Student" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Course" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Subject" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Semester" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SchoolYear" RESTART IDENTITY CASCADE;

-- Re-enable FKs
SET session_replication_role = DEFAULT;

